#line 1 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"

#line 3 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer D_yyFlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

#ifdef yyalloc
#define D_yyalloc_ALREADY_DEFINED
#else
#define yyalloc D_yyalloc
#endif

#ifdef yyrealloc
#define D_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc D_yyrealloc
#endif

#ifdef yyfree
#define D_yyfree_ALREADY_DEFINED
#else
#define yyfree D_yyfree
#endif

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::streambuf* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

inline int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int Lexer::yylex()

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 131
#define YY_END_OF_BUFFER 132
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[440] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    2,    2,  132,  131,  129,    5,  120,  128,
        6,  115,  116,  124,  121,  114,  122,  105,  123,   17,
      125,  108,  126,  107,  127,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  112,  119,  113,  117,  118,    4,
       15,    7,  131,   16,    8,  131,    3,    2,  129,   17,
       17,   17,    0,  106,  111,  110,  109,  130,  130,  130,
      130,  130,  130,  130,  130,   44,  130,  130,  130,  130,
      130,  130,   35,  130,  130,  130,  130,  130,  130,  130,

       53,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,   59,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,    0,    0,    0,    0,    0,    0,   25,
       24,    0,   23,   15,   14,   12,    9,   11,   10,   16,
       13,    3,    2,    0,    0,    0,   17,  130,  130,   52,
      130,  130,  130,  130,  130,  130,  130,  130,  130,   58,
      130,  130,  130,  130,  130,   54,  130,   34,  130,   79,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
       88,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,   81,  130,  130,  130,  130,  130,  130,  130,    0,

       33,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       17,    0,   17,  130,  130,   66,   65,   78,   50,  130,
      130,  130,   38,  130,  130,  130,  130,  130,  130,  130,
      130,   60,   98,  130,  130,  130,  130,  130,   86,  130,
       97,   71,   48,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,   91,  130,   90,   46,   19,   40,  130,
      130,   55,  130,   20,  130,  130,  130,  130,  130,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  130,  130,
      130,  130,   84,  130,  130,  130,  130,  130,   41,  130,
      130,  130,  130,  130,   56,  130,  100,  130,  130,  130,

       69,   68,  130,  130,  130,  130,   89,   57,  130,  130,
      130,   94,  130,  130,  130,  130,  130,  130,  130,  130,
      130,   43,  130,  130,   32,    0,    0,    0,    0,    0,
        0,   27,   21,   92,  130,  130,  130,  130,  130,   39,
       61,  130,  130,  130,  130,  130,  130,    1,  130,   72,
      130,   18,  130,  102,  130,   42,  130,  130,  130,   80,
      130,  130,   93,   95,  130,  130,  130,  130,  130,   31,
        0,    0,    0,    0,    0,   62,   67,  130,  130,   51,
       99,  130,   49,  130,   47,  130,  130,  130,  104,  101,
      130,  130,  130,  130,   85,  130,  130,  130,  130,  130,

        0,    0,    0,    0,    0,  130,  130,  130,  130,   45,
      130,   63,  130,   37,  130,   74,   87,  130,   36,   77,
       76,   29,   26,   28,    0,    0,   64,   70,   73,  103,
      130,   82,   75,   96,   22,   30,  130,   83,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    1,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,    1,   53,    1,   54,   55,   56,   57,

       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   40,   70,   71,   72,   73,   74,   75,   76,
       77,   78,   79,   40,   80,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[81] =
    {   0,
        1,    2,    3,    2,    1,    4,    1,    1,    5,    1,
        1,    1,    1,    1,    1,    1,    1,    6,    1,    1,
        1,    1,    1,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        7,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    1,    1
    } ;

static const flex_int16_t yy_base[450] =
    {   0,
        0,    0,    0,    0,  210,  173,   75,   76,   74,   77,
        0,    0,   85,   88,  175,  926,    0,  926,  926,  926,
      926,  926,  926,  926,  926,  926,  926,  153,  926,   77,
      146,  926,   62,  926,  141,   73,   56,   77,   74,   69,
       79,    0,   71,   71,   73,   78,  115,  120,  129,  126,
      142,  134,  177,  121,  926,  220,  926,  926,  926,  926,
        0,  926,  200,    0,  926,  177,    0,  158,    0,  176,
      181,  232,  164,  926,  926,  926,  926,    0,  199,  164,
      197,  186,   79,  191,  249,    0,  165,  224,  239,  191,
      237,  240,    0,  240,  242,  251,  257,  221,  261,  256,

        0,  247,  261,  265,  290,  281,  294,  283,  293,  278,
      281,  284,  286,  289,  294,  298,  305,  311,  312,  310,
      315,  325,  316,  318,  332,  334,  322,  330,  343,  340,
      926,  338,  926,    0,  926,  926,  926,  926,  926,    0,
      926,    0,  153,  204,  366,  135,  101,  340,  341,    0,
      361,  356,  364,  352,  371,  374,  372,  402,  361,    0,
      369,  381,  371,  360,  373,  369,  388,    0,  384,  395,
      373,  376,  398,  387,  387,  393,  423,  412,  414,  423,
      433,  434,  424,  434,  433,  426,  427,  436,  440,  437,
      448,    0,  437,  453,  440,  457,  452,  455,  463,  457,

      926,  456,  453,  473,  474,  480,  473,  473,  488,  100,
       95,   80,   79,  487,  479,  491,  480,    0,    0,  480,
      483,  483,  488,  492,  499,  495,  494,  509,  510,  509,
      514,    0,    0,  503,  504,  505,  518,  545,    0,  526,
        0,    0,    0,  529,  518,  523,  523,  523,  533,  538,
      548,  541,  554,    0,  545,    0,    0,    0,    0,  558,
      554,    0,  561,    0,  563,  566,  566,  569,  570,  572,
      563,  561,  564,  576,  578,  589,  583,  588,  582,  590,
      592,  591,    0,  593,  595,  609,  599,  604,    0,  615,
      607,  620,  607,  618,    0,  610,    0,  612,  628,  632,

        0,    0,  620,  631,  635,  626,    0,    0,  628,  626,
      646,    0,  646,  644,  653,  636,  638,  651,  653,  652,
      667,    0,  669,  673,  926,  657,  669,  673,  675,  669,
      680,  926,  926,    0,  668,  685,  690,  679,  675,    0,
        0,  694,  678,  698,  687,  686,  691,    0,  706,    0,
      691,    0,  696,    0,  702,    0,  708,  698,  719,    0,
      702,  720,    0,    0,  713,  709,  710,  714,  716,  926,
      725,  734,  722,  742,  734,    0,    0,  730,  740,    0,
        0,  740,    0,  736,    0,  752,  742,  751,    0,    0,
      757,  763,  746,  766,    0,  764,  763,  773,  774,  777,

      775,  765,  773,  772,  785,  768,  770,  788,  792,    0,
      791,    0,  780,    0,  800,    0,    0,  791,    0,    0,
        0,  926,  926,  926,  801,  800,    0,    0,    0,    0,
      804,    0,    0,    0,  926,  926,  792,    0,  926,  864,
      871,  878,  885,  892,   90,  899,  905,  912,  918
    } ;

static const flex_int16_t yy_def[450] =
    {   0,
      439,    1,  440,  440,    1,    1,  441,  441,  442,  442,
      440,  440,  443,  443,  439,  439,  444,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  439,  439,  439,  439,  439,  439,
      446,  439,  447,  448,  439,  447,  449,  439,  444,  439,
      439,  439,  439,  439,  439,  439,  439,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  446,  439,  439,  439,  439,  439,  448,
      439,  449,  439,  439,  439,  439,  439,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  439,

      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  439,
      439,  439,  439,  439,  439,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      439,  439,  439,  439,  439,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  439,  439,  439,  439,  439,  445,  445,  445,  445,
      445,  445,  445,  445,  439,  439,  445,  445,    0,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439
    } ;

static const flex_int16_t yy_nxt[1007] =
    {   0,
       16,   16,   16,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       42,   43,   44,   42,   42,   45,   46,   47,   48,   42,
       49,   50,   51,   42,   52,   53,   42,   42,   54,   55,
       56,   57,   16,   36,   37,   38,   39,   40,   41,   42,
       42,   43,   44,   42,   42,   45,   46,   47,   48,   49,
       50,   51,   42,   52,   53,   42,   42,   54,   58,   59,
       62,   62,   65,   75,   76,   65,   68,   16,   16,   68,
       16,   16,   71,   82,   72,   78,  213,  213,   79,   93,

       83,   85,   89,   87,   73,   88,   94,   95,   96,   80,
       97,   86,  211,   81,   84,   98,   90,  211,  147,   91,
      153,   99,   92,   82,   66,   63,   63,   66,   79,   93,
       83,   85,   89,   87,   73,   88,   94,   95,   96,   80,
       97,   86,   81,  100,   84,   98,   90,  102,   91,  153,
       99,   92,  147,  107,  143,  101,  105,  116,  123,  143,
      103,  117,   77,  104,  108,  110,  106,   74,  109,  111,
       70,  118,  112,  100,  439,   60,  146,  102,  146,  113,
      114,  147,  115,  107,  101,  141,  105,  116,  123,  103,
      150,  117,  104,   70,  108,  110,  106,  109,   70,  111,

      119,  118,  112,  144,  120,  136,  157,  121,  145,  113,
      114,  115,   60,  137,  122,  439,  210,  138,  210,  139,
      150,  211,  151,  152,  148,  439,  439,  154,  439,  439,
      119,  160,  439,  144,  120,  157,  137,  121,  145,  439,
      138,  149,  139,  137,  122,  124,  138,   71,  139,   72,
      158,  125,  151,  152,  148,  126,  127,  154,  128,   73,
      160,  129,  130,  168,  131,  132,  137,  439,  133,  138,
      149,  139,  155,  159,  161,  124,  162,  156,  163,  164,
      158,  125,  165,  166,  171,  126,  127,  172,  128,   73,
      129,  130,  168,  131,  132,  169,  170,  133,  173,  174,

      439,  167,  155,  159,  161,  179,  162,  156,  163,  164,
      182,  188,  165,  166,  171,  175,  172,  180,  439,  185,
      183,  439,  186,  189,  176,  169,  170,  187,  173,  174,
      167,  177,  178,  184,  190,  179,  181,  191,  192,  193,
      182,  188,  194,  195,  196,  175,  197,  180,  185,  198,
      183,  186,  199,  189,  176,  200,  187,  203,  201,  204,
      177,  178,  184,  190,  205,  181,  191,  192,  202,  193,
      206,  207,  194,  195,  196,  209,  197,  208,  212,  198,
      212,  214,  199,  213,  215,  200,  216,  203,  201,  204,
      218,  219,  439,  220,  205,  217,  221,  222,  202,  223,

      206,  207,  231,  235,  232,  209,  233,  208,  234,  236,
      214,  439,  237,  215,  241,  238,  216,  242,  239,  240,
      218,  219,  220,  243,  245,  217,  221,  222,  244,  223,
      224,  231,  235,  225,  232,  246,  233,  226,  234,  236,
      227,  237,  228,  241,  229,  238,  242,  230,  239,  240,
      247,  439,  248,  243,  245,  249,  250,  244,  251,  252,
      224,  253,  254,  225,  246,  255,  256,  226,  257,  258,
      227,  228,  259,  229,  260,  262,  230,  261,  263,  264,
      247,  248,  265,  266,  249,  250,  267,  268,  251,  252,
      269,  253,  254,  270,  271,  255,  256,  257,  258,  272,

      273,  274,  259,  275,  260,  262,  261,  263,  276,  264,
      277,  265,  278,  266,  279,  280,  267,  268,  281,  286,
      269,  282,  283,  270,  271,  284,  285,  289,  272,  287,
      273,  274,  290,  275,  291,  288,  292,  293,  276,  294,
      277,  295,  278,  296,  279,  280,  297,  298,  281,  286,
      282,  283,  299,  303,  284,  285,  304,  289,  305,  287,
      306,  310,  290,  291,  288,  307,  292,  293,  300,  294,
      308,  295,  296,  309,  311,  297,  298,  301,  312,  302,
      313,  314,  299,  303,  315,  316,  304,  305,  317,  318,
      306,  310,  321,  322,  307,  323,  324,  325,  300,  308,

      326,  328,  309,  327,  311,  319,  320,  301,  312,  302,
      313,  314,  329,  330,  315,  316,  331,  332,  317,  318,
      333,  335,  321,  322,  334,  323,  324,  325,  336,  339,
      326,  328,  327,  337,  319,  320,  338,  340,  439,  341,
      342,  343,  329,  330,  344,  345,  331,  332,  346,  347,
      333,  335,  348,  334,  349,  350,  351,  353,  336,  339,
      352,  354,  337,  355,  356,  338,  357,  340,  341,  358,
      342,  343,  359,  360,  344,  345,  361,  346,  362,  347,
      363,  348,  364,  349,  365,  350,  351,  353,  366,  352,
      367,  354,  368,  355,  356,  357,  369,  439,  370,  358,

      371,  372,  359,  360,  373,  374,  361,  362,  375,  363,
      376,  377,  364,  378,  365,  379,  439,  380,  366,  381,
      367,  382,  368,  383,  384,  386,  369,  370,  385,  387,
      371,  372,  388,  389,  373,  374,  390,  391,  375,  376,
      392,  377,  393,  378,  394,  379,  380,  395,  396,  381,
      382,  397,  398,  383,  384,  386,  399,  385,  400,  387,
      401,  388,  402,  389,  403,  404,  390,  391,  405,  392,
      406,  407,  393,  394,  408,  439,  409,  395,  396,  410,
      397,  398,  411,  412,  413,  399,  414,  400,  415,  416,
      401,  417,  402,  403,  418,  404,  419,  420,  405,  406,

      421,  407,  422,  424,  408,  409,  423,  425,  426,  410,
      427,  411,  428,  412,  413,  429,  414,  415,  430,  416,
      431,  417,  432,  433,  418,  434,  419,  420,  435,  436,
      421,  437,  422,  424,  438,  423,  439,  425,  426,  427,
      439,  428,  439,  439,  439,  429,  439,  439,  430,  439,
      431,  432,  439,  433,  439,  434,  439,  439,  435,  436,
      439,  437,  439,  438,   16,   16,   16,   16,   16,   16,
       16,   61,   61,   61,   61,   61,   61,   61,   64,   64,
       64,   64,   64,   64,   64,   67,   67,   67,   67,   67,
       67,   67,   69,   69,  439,   69,   69,   69,   69,  134,

      134,  134,  439,  134,  134,  135,  135,  135,  135,  135,
      135,  135,  140,  140,  140,  140,  439,  140,  142,  439,
      439,  142,  142,  142,  142,   15,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,

      439,  439,  439,  439,  439,  439
    } ;

static const flex_int16_t yy_chk[1007] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        7,    8,    9,   33,   33,   10,   13,   13,   13,   14,
       14,   14,   30,   37,   30,  445,  213,  212,   36,   43,

       38,   39,   41,   40,   30,   40,   43,   43,   44,   36,
       45,   39,  211,   36,   38,   46,   41,  210,  147,   41,
       83,   46,   41,   37,    9,    7,    8,   10,   36,   43,
       38,   39,   41,   40,   30,   40,   43,   43,   44,   36,
       45,   39,   36,   47,   38,   46,   41,   48,   41,   83,
       46,   41,  146,   50,  143,   47,   49,   52,   54,   68,
       48,   52,   35,   48,   50,   51,   49,   31,   50,   51,
       28,   52,   51,   47,   15,    6,   73,   48,   73,   51,
       51,   73,   51,   50,   47,   66,   49,   52,   54,   48,
       80,   52,   48,   70,   50,   51,   49,   50,   71,   51,

       53,   52,   51,   70,   53,   63,   87,   53,   71,   51,
       51,   51,    5,   66,   53,    0,  144,   66,  144,   66,
       80,  144,   81,   82,   79,    0,    0,   84,    0,    0,
       53,   90,    0,   70,   53,   87,   63,   53,   71,    0,
       63,   79,   63,   66,   53,   56,   66,   72,   66,   72,
       88,   56,   81,   82,   79,   56,   56,   84,   56,   72,
       90,   56,   56,   98,   56,   56,   63,    0,   56,   63,
       79,   63,   85,   89,   91,   56,   92,   85,   94,   95,
       88,   56,   96,   97,  100,   56,   56,  102,   56,   72,
       56,   56,   98,   56,   56,   99,   99,   56,  103,  104,

        0,   97,   85,   89,   91,  106,   92,   85,   94,   95,
      108,  112,   96,   97,  100,  105,  102,  107,    0,  110,
      109,    0,  111,  113,  105,   99,   99,  111,  103,  104,
       97,  105,  105,  109,  114,  106,  107,  115,  116,  117,
      108,  112,  118,  119,  120,  105,  121,  107,  110,  122,
      109,  111,  123,  113,  105,  124,  111,  126,  125,  127,
      105,  105,  109,  114,  128,  107,  115,  116,  125,  117,
      129,  130,  118,  119,  120,  132,  121,  130,  145,  122,
      145,  148,  123,  145,  149,  124,  151,  126,  125,  127,
      152,  153,    0,  154,  128,  151,  155,  156,  125,  157,

      129,  130,  159,  164,  161,  132,  162,  130,  163,  165,
      148,    0,  166,  149,  171,  167,  151,  172,  169,  170,
      152,  153,  154,  173,  175,  151,  155,  156,  174,  157,
      158,  159,  164,  158,  161,  176,  162,  158,  163,  165,
      158,  166,  158,  171,  158,  167,  172,  158,  169,  170,
      177,    0,  178,  173,  175,  178,  179,  174,  180,  181,
      158,  182,  183,  158,  176,  184,  185,  158,  186,  187,
      158,  158,  188,  158,  189,  191,  158,  190,  193,  194,
      177,  178,  195,  196,  178,  179,  197,  198,  180,  181,
      199,  182,  183,  200,  202,  184,  185,  186,  187,  203,

      204,  205,  188,  206,  189,  191,  190,  193,  207,  194,
      208,  195,  209,  196,  214,  215,  197,  198,  216,  223,
      199,  217,  220,  200,  202,  221,  222,  225,  203,  224,
      204,  205,  226,  206,  227,  224,  228,  229,  207,  230,
      208,  231,  209,  234,  214,  215,  235,  236,  216,  223,
      217,  220,  237,  240,  221,  222,  244,  225,  245,  224,
      246,  250,  226,  227,  224,  247,  228,  229,  238,  230,
      248,  231,  234,  249,  251,  235,  236,  238,  252,  238,
      253,  255,  237,  240,  260,  261,  244,  245,  263,  265,
      246,  250,  266,  267,  247,  268,  269,  270,  238,  248,

      271,  273,  249,  272,  251,  265,  265,  238,  252,  238,
      253,  255,  274,  275,  260,  261,  276,  277,  263,  265,
      278,  280,  266,  267,  279,  268,  269,  270,  281,  285,
      271,  273,  272,  282,  265,  265,  284,  286,    0,  287,
      288,  290,  274,  275,  291,  292,  276,  277,  293,  294,
      278,  280,  296,  279,  298,  299,  300,  304,  281,  285,
      303,  305,  282,  306,  309,  284,  310,  286,  287,  311,
      288,  290,  313,  314,  291,  292,  315,  293,  316,  294,
      317,  296,  318,  298,  319,  299,  300,  304,  320,  303,
      321,  305,  323,  306,  309,  310,  324,    0,  326,  311,

      327,  328,  313,  314,  329,  330,  315,  316,  331,  317,
      335,  336,  318,  337,  319,  338,    0,  339,  320,  342,
      321,  343,  323,  344,  345,  347,  324,  326,  346,  349,
      327,  328,  351,  353,  329,  330,  355,  357,  331,  335,
      358,  336,  359,  337,  361,  338,  339,  362,  365,  342,
      343,  366,  367,  344,  345,  347,  368,  346,  369,  349,
      371,  351,  372,  353,  373,  374,  355,  357,  375,  358,
      378,  379,  359,  361,  382,    0,  384,  362,  365,  386,
      366,  367,  387,  388,  391,  368,  392,  369,  393,  394,
      371,  396,  372,  373,  397,  374,  398,  399,  375,  378,

      400,  379,  401,  403,  382,  384,  402,  404,  405,  386,
      406,  387,  407,  388,  391,  408,  392,  393,  409,  394,
      411,  396,  413,  415,  397,  418,  398,  399,  425,  426,
      400,  431,  401,  403,  437,  402,    0,  404,  405,  406,
        0,  407,    0,    0,    0,  408,    0,    0,  409,    0,
      411,  413,    0,  415,    0,  418,    0,    0,  425,  426,
        0,  431,    0,  437,  440,  440,  440,  440,  440,  440,
      440,  441,  441,  441,  441,  441,  441,  441,  442,  442,
      442,  442,  442,  442,  442,  443,  443,  443,  443,  443,
      443,  443,  444,  444,    0,  444,  444,  444,  444,  446,

      446,  446,    0,  446,  446,  447,  447,  447,  447,  447,
      447,  447,  448,  448,  448,  448,    0,  448,  449,    0,
        0,  449,  449,  449,  449,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,

      439,  439,  439,  439,  439,  439
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[132] =
    {   0,
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static const flex_int16_t yy_rule_linenum[131] =
    {   0,
      173,  174,  175,  210,  229,  230,  232,  236,  241,  242,
      243,  244,  245,  247,  249,  250,  257,  266,  267,  268,
      270,  271,  272,  273,  274,  275,  276,  277,  278,  279,
      280,  281,  282,  284,  285,  286,  287,  288,  289,  290,
      291,  292,  293,  294,  295,  296,  297,  298,  299,  300,
      301,  302,  303,  304,  306,  307,  308,  309,  310,  311,
      312,  315,  316,  317,  318,  319,  320,  321,  322,  323,
      327,  328,  329,  330,  331,  332,  333,  334,  335,  336,
      337,  338,  339,  340,  341,  342,  344,  345,  346,  347,
      348,  351,  352,  353,  354,  355,  356,  357,  358,  359,

      360,  361,  362,  363,  367,  368,  369,  370,  371,  372,
      373,  374,  375,  376,  377,  378,  379,  380,  381,  382,
      383,  384,  385,  386,  387,  388,  389,  390,  391,  393
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <QString>
#include <string>
#include <stack>
#include <iostream>
#include <cerrno>
#include <climits>
#include <stdio.h>
#include <fstream>
#include "lexer.hpp"
typedef Language::Parser::token token;
#define yyterminate() return( token::END )
#define YY_NO_UNISTD_H // For msvc


extern "C" int yywrap() { return 1; }
using namespace Language;

#define YYERROR_VERBOSE 1
Language::location loc;//ÉùÃ÷Î»ÖÃÊµÀý

std::string cur_yytext;
std::string g_str;
int yycolumn = 1;
int yylineno = 1;
int current_line_indent = 0;   /* indentation of the current line */
int indent_level = 0;          /* indentation level passed to the parser */
std::stack<int> curr_indents;
int first_time = 1 ;

int parsing_error = 0;

std::stack<std::string> fileNames;
std::stack<int> lineNo;
std::vector<std::string> libPaths;



#define YY_USER_ACTION do { \
    if( loc.end.line < yylineno ) yycolumn = 1 ; \
    loc.begin.line = loc.end.line = yylineno; \
    loc.begin.column = yycolumn; loc.end.column = yycolumn + (int)yyleng - 1; \
    yycolumn += (int)yyleng; \
    loc.end.filename = &(fileNames.top()); \
    } while(0) ;

int yyerror(char const * s )
{
    printf("ERROR %s  at line %d col %d\n", s,  yylineno, yycolumn);
    printf("parsed %s %d.%d-%d.%d\n", loc.end.filename->c_str(), loc.begin.line, loc.begin.column, loc.end.line, loc.end.column);
    return 1;
}

#line 965 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"
 
#line 967 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"

#define INITIAL 0
#define indent 1
#define normal 2
#define str 3
#define qstr 4
#define comment 5
#define incl 6

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin.rdbuf(std::cin.rdbuf());
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout.rdbuf(std::cout.rdbuf());
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 160 "lexer.l"




#line 165 "lexer.l"
            if( first_time ) {
                first_time = 0;
                curr_indents.push(0);
                lineNo.push(yylineno);
                BEGIN normal;
            }

            
#line 1172 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 440 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 926 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 131 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 131 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 132 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 173 "lexer.l"
BEGIN(incl);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 174 "lexer.l"
/* eat the whitespace */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 175 "lexer.l"
{ /* got the include file name */
                    std::string fileName = yytext;
                    std::size_t pos = fileName.find(".liq");
                    if( pos == std::string::npos ) {
                        fileName += ".liq";
                    }
                    std::string filePath="";
                    for( auto libpath : libPaths ) {
                       filePath = libpath + fileName;
                       std::ifstream file(filePath.c_str());
                       if(file.good())
                          break;
                    }
                    std::filebuf fb;
                    if (fb.open (filePath,std::ios::in))
                    {
                         std::istream is(&fb);
                         //yyin = is;
                         fileNames.push(std::string(yytext));
                         lineNo.push(yylineno);
                         yylineno = yycolumn = 1;
                         loc.begin.line = loc.begin.column = loc.end.line = loc.end.column = 1;
                         yypush_buffer_state(yy_create_buffer( is, YY_BUF_SIZE ));
                         fb.close();
                    }
                    else
                    {
                         printf( "%s in %s line %d\n", (std::string("Failed to load import file ") + fileName).c_str(), fileNames.top().c_str(), yylineno );
                         parsing_error = 1;
                         yyterminate();
                    }

                    BEGIN(normal);
                    }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 210 "lexer.l"
{ current_line_indent = 0; /*BEGIN( indent);*/ yycolumn = 1; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(indent):
case YY_STATE_EOF(normal):
case YY_STATE_EOF(str):
case YY_STATE_EOF(qstr):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(incl):
#line 211 "lexer.l"
{
                   if( curr_indents.size() > 1 ) {
                        curr_indents.pop();
                        return token::UNINDENT;
                   }
                   if(lineNo.size() > 1 ) {
                       yypop_buffer_state();
                       fileNames.pop();
                       yylineno = lineNo.top();
                       lineNo.pop();
                   } else {
                        yyterminate();
                   }
                 }			 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 229 "lexer.l"
g_str = ""; BEGIN(str);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 230 "lexer.l"
g_str = ""; BEGIN(qstr);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 232 "lexer.l"
{   BEGIN(normal);
            yylval->sval = new QString(QString::fromStdString(g_str));
            return token::String;
        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 236 "lexer.l"
{   BEGIN(normal);
            yylval->sval = new QString(QString::fromStdString(g_str));
            return token::String;
        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 241 "lexer.l"
{g_str += "\n";}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 242 "lexer.l"
g_str += "\t";
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 243 "lexer.l"
g_str += "\r";
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 244 "lexer.l"
g_str += "\"";
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 245 "lexer.l"
g_str += "'";
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 247 "lexer.l"
{g_str += yytext[1]; cur_yytext=yytext[1];}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 249 "lexer.l"
{g_str += std::string(yytext);cur_yytext=yytext;}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 250 "lexer.l"
{g_str += std::string(yytext);cur_yytext=yytext;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 257 "lexer.l"
{
                                                        yylval->dval = atof(yytext);
                                                        cur_yytext=yytext;
                                                        return token::Number;
                                                }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 266 "lexer.l"
{ return token::NumberType; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 267 "lexer.l"
{ return token::TextType; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 268 "lexer.l"
{ return token::VoidType; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 270 "lexer.l"
{ return token::WOBJ_P; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 271 "lexer.l"
{ return token::SEAM_NAME; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 272 "lexer.l"
{ return token::ZONE_P; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 273 "lexer.l"
{ return token::VEL_P; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 274 "lexer.l"
{ return token::TCP_P; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 275 "lexer.l"
{ return token::NOEOFFS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 276 "lexer.l"
{ return token::TOOL_P; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 277 "lexer.l"
{ return token::PLEN; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 278 "lexer.l"
{ return token::MAXTIME; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 279 "lexer.l"
{ return token::TIMEFLAG; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 280 "lexer.l"
{ return token::INPOS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 281 "lexer.l"
{ return token::CONC; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 282 "lexer.l"
{ return token::ID_P; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 284 "lexer.l"
{ return token::NOT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 285 "lexer.l"
{ return token::IF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 286 "lexer.l"
{return token::WELDDATA;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 287 "lexer.l"
{return token::SEAMDATA;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 288 "lexer.l"
{ return token::ELSE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 289 "lexer.l"
{ return token::ELSEIF; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 290 "lexer.l"
{ return token::THEN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 291 "lexer.l"
{ return token::ENDIF; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 292 "lexer.l"
{ return token::RETURN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 293 "lexer.l"
{return token::WHILE;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 294 "lexer.l"
{return token::DO;}   
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 295 "lexer.l"
{return token::ENDWHILE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 296 "lexer.l"
{return token::TEST;}   	
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 297 "lexer.l"
{return token::ENDTEST;}   	
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 298 "lexer.l"
{return token::PROC;}  
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 299 "lexer.l"
{return token::ENDPROC;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 300 "lexer.l"
{return token::CASE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 301 "lexer.l"
{return token::DEFAULT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 302 "lexer.l"
{return token::AND;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 303 "lexer.l"
{return token::OR;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 304 "lexer.l"
{ return token::MOD;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 306 "lexer.l"
{return token::FTRUE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 307 "lexer.l"
{return token::FFALSE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 308 "lexer.l"
{return token::RETRY;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 309 "lexer.l"
{return token::FOR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 310 "lexer.l"
{return token::TO;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 311 "lexer.l"
{return token::FROM;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 312 "lexer.l"
{return token::ENDFOR;}   
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 315 "lexer.l"
{return token::ACTUNIT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 316 "lexer.l"
{return token::MOVEABSJ;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 317 "lexer.l"
{return token::ARCLSTART;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 318 "lexer.l"
{return token::ARCL;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 319 "lexer.l"
{return token::ARCC;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 320 "lexer.l"
{return token::ARCEND;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 321 "lexer.l"
{return token::MOVEL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 322 "lexer.l"
{return token::MOVEJ;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 323 "lexer.l"
{return token::DEACTUNIT;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 327 "lexer.l"
{return token::PERS;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 328 "lexer.l"
{return token::MODULE;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 329 "lexer.l"
{return token::ENDMODULE;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 330 "lexer.l"
{return token::TOOLDATA;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 331 "lexer.l"
{return token::SPEEDDATA;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 332 "lexer.l"
{return token::ZONEDATA;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 333 "lexer.l"
{return token::WOBJDATA;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 334 "lexer.l"
{return token::BOOL;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 335 "lexer.l"
{return token::NUM;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 336 "lexer.l"
{return token::STRING;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 337 "lexer.l"
{return token::VAR;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 338 "lexer.l"
{return token::ROBTARGET;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 339 "lexer.l"
{return token::JOINTTARGET;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 340 "lexer.l"
{return token::CONST_L;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 341 "lexer.l"
{return token::TPWRITE;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 342 "lexer.l"
{return token::FNULL;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 344 "lexer.l"
{return token::WAITTIME;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 345 "lexer.l"
{return token::SET;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 346 "lexer.l"
{return token::RESET;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 347 "lexer.l"
{return token::TASK;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 348 "lexer.l"
{return token::STEP;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 351 "lexer.l"
{return token::ACCSET;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 352 "lexer.l"
{return token::VELSET;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 353 "lexer.l"
{return token::SETDO;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 354 "lexer.l"
{return token::WAITDI;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 355 "lexer.l"
{return token::WAITUNTIL;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 356 "lexer.l"
{return token::OFFS;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 357 "lexer.l"
{return token::FUNC;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 358 "lexer.l"
{ return token::ENDFUNC; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 359 "lexer.l"
{return token::INOUT;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 360 "lexer.l"
{return token::RELTOOl;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 361 "lexer.l"
{return token::RECORD;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 362 "lexer.l"
{return token::ENDRECORD;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 363 "lexer.l"
{return token::PULSEDO;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 367 "lexer.l"
{return token::DOT;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 368 "lexer.l"
{return token::ASS;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 369 "lexer.l"
{return token::EQ;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 370 "lexer.l"
{ return token::SEMICOLON; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 371 "lexer.l"
{ return token::GE; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 372 "lexer.l"
{ return token::NE; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 373 "lexer.l"
{ return token::LE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 374 "lexer.l"
{ return token::LR; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 375 "lexer.l"
{ return token::RR; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 376 "lexer.l"
{ return token::COMMA; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 377 "lexer.l"
{ return token::LC; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 378 "lexer.l"
{ return token::RC; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 379 "lexer.l"
{ return token::LBRACE; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 380 "lexer.l"
{ return token::RBRACE; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 381 "lexer.l"
{return token::SPLASH;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 382 "lexer.l"
{return token::JIN;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 383 "lexer.l"
{ return token::ADD; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 384 "lexer.l"
{ return token::SUB; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 385 "lexer.l"
{ return token::DIVIDE; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 386 "lexer.l"
{ return token::MUL; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 387 "lexer.l"
{ return token::COLON; }  
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 388 "lexer.l"
{return token::LT;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 389 "lexer.l"
{return token::GT;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 390 "lexer.l"
{return token::DOLAR;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 391 "lexer.l"
/* comments one line til nl */
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 393 "lexer.l"
{
                                                        yylval->sval = new QString( yytext );
                                                        cur_yytext=yytext;
                                                        return( token::Identifier );
                                             }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 403 "lexer.l"
ECHO;
	YY_BREAK
#line 1990 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 440 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 440 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 439);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, char* yy_bp)
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream& input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_input_file = file.rdbuf();
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int _new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 403 "lexer.l"






