#line 1 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"

#line 3 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer D_yyFlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

#ifdef yyalloc
#define D_yyalloc_ALREADY_DEFINED
#else
#define yyalloc D_yyalloc
#endif

#ifdef yyrealloc
#define D_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc D_yyrealloc
#endif

#ifdef yyfree
#define D_yyfree_ALREADY_DEFINED
#else
#define yyfree D_yyfree
#endif

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::streambuf* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

inline int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int Lexer::yylex()

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 132
#define YY_END_OF_BUFFER 133
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[443] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    2,    2,  133,  132,   56,  130,    5,  121,
      129,    6,  117,  118,  125,  122,  116,  123,  107,  124,
       17,  126,  110,  127,  109,  128,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  114,  132,  115,  119,  120,
        4,   15,    7,  132,   16,    8,  132,    3,    2,   56,
      130,   18,   18,   17,    0,  108,  113,  112,  111,  131,
      131,  131,  131,  131,  131,  131,  131,   45,  131,  131,
      131,  131,  131,  131,   36,  131,  131,  131,  131,  131,

      131,  131,   54,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,   61,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,    0,    0,    0,    0,    0,
        0,    0,   26,   25,    0,   24,   15,   14,   12,    9,
       11,   10,   16,   13,    3,    2,    0,    0,    0,   17,
      131,  131,   53,  131,  131,  131,  131,  131,  131,  131,
      131,  131,   60,  131,  131,  131,  131,  131,   55,  131,
       35,  131,   81,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,   90,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,   83,  131,  131,  131,  131,  131,

      131,  131,    0,   34,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   18,    0,   18,  131,  131,   68,   67,
       80,   51,  131,  131,  131,   39,  131,  131,  131,  131,
      131,  131,  131,  131,   62,  100,  131,  131,  131,  131,
      131,   88,  131,   99,   73,   49,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,   93,  131,   92,   47,
       20,   41,  131,  131,   57,  131,   21,  131,  131,  131,
      131,  131,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  131,  131,  131,  131,   86,  131,  131,  131,  131,
      131,   42,  131,  131,  131,  131,  131,   58,  131,  102,

      131,  131,  131,   71,   70,  131,  131,  131,  131,   91,
       59,  131,  131,  131,   96,  131,  131,  131,  131,  131,
      131,  131,  131,  131,   44,  131,  131,   33,    0,    0,
        0,    0,    0,    0,   28,   22,   94,  131,  131,  131,
      131,  131,   40,   63,  131,  131,  131,  131,  131,  131,
        1,  131,   74,  131,   19,  131,  104,  131,   43,  131,
      131,  131,   82,  131,  131,   95,   97,  131,  131,  131,
      131,  131,   32,    0,    0,    0,    0,    0,   64,   69,
      131,  131,   52,  101,  131,   50,  131,   48,  131,  131,
      131,  106,  103,  131,  131,  131,  131,   87,  131,  131,

      131,  131,  131,    0,    0,    0,    0,    0,  131,  131,
      131,  131,   46,  131,   65,  131,   38,  131,   76,   89,
      131,   37,   79,   78,   30,   27,   29,    0,    0,   66,
       72,   75,  105,  131,   84,   77,   98,   23,   31,  131,
       85,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    8,    9,    1,    1,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,    1,   54,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   41,   71,   72,   73,   74,   75,   76,   77,
       78,   79,   80,   41,   81,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[82] =
    {   0,
        1,    2,    3,    1,    2,    1,    4,    1,    1,    5,
        1,    1,    1,    1,    1,    1,    1,    1,    6,    1,
        1,    1,    1,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    7,    1,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1
    } ;

static const flex_int16_t yy_base[453] =
    {   0,
        0,    0,    0,    0,  228,  220,   75,   76,   74,   77,
        0,    0,   83,   87,  220,  945,   91,    0,  945,  945,
      945,  945,  945,  945,  945,  945,  945,  945,  167,  945,
       80,  161,  945,   77,  945,  160,   64,   64,   79,   78,
       72,  111,    0,  121,   72,   73,   75,   83,  128,  132,
      134,  171,  169,  190,   76,  945,  258,  945,  945,  945,
      232,    0,  945,  183,    0,  945,  206,    0,  175,  259,
        0,  133,  136,  150,  198,  945,  945,  945,  945,    0,
      226,   88,  103,  136,  125,  138,  251,    0,  175,  211,
      207,  204,  218,  220,    0,  227,  241,  249,  261,  211,

      256,  256,    0,  223,  251,  273,  302,  287,  307,  285,
      298,  228,  299,  289,  285,  288,  296,  307,  316,  320,
      322,  320,  325,  334,  323,  170,  324,  339,  340,  327,
      336,  344,  348,  945,  340,  945,    0,  945,  945,  945,
      945,  945,    0,  945,    0,  162,  385,  394,  112,  105,
      346,  347,    0,  378,  358,  369,  357,  379,  387,  386,
      416,  376,    0,  383,  395,  386,  385,  389,  387,  405,
        0,  401,  412,  390,  397,  414,  400,  408,  407,  425,
      428,  421,  429,  446,  446,  438,  448,  447,  441,  444,
      452,  455,  451,  466,    0,  454,  470,  456,  473,  467,

      472,  478,  471,  945,  470,  465,  486,  487,  493,  482,
      484,  498,  104,  103,  100,   86,  498,  492,  503,  491,
        0,    0,  491,  494,  496,  510,  505,  517,  512,  513,
      523,  527,  526,  530,    0,    0,  519,  521,  522,  532,
      544,    0,  542,    0,    0,    0,  543,  533,  537,  539,
      536,  545,  566,  564,  554,  568,    0,  559,    0,    0,
        0,    0,  572,  570,    0,  576,    0,  587,  579,  580,
      583,  585,  590,  579,  576,  585,  587,  591,  600,  598,
      602,  594,  607,  604,  600,    0,  601,  614,  621,  611,
      618,    0,  629,  623,  636,  622,  635,    0,  627,    0,

      630,  640,  650,    0,    0,  636,  651,  655,  645,    0,
        0,  647,  646,  664,    0,  662,  660,  670,  653,  657,
      669,  671,  667,  683,    0,  685,  686,  945,  673,  679,
      688,  691,  685,  694,  945,  945,    0,  683,  700,  704,
      693,  689,    0,    0,  709,  694,  710,  704,  702,  708,
        0,  722,    0,  706,    0,  711,    0,  715,    0,  724,
      713,  735,    0,  719,  735,    0,    0,  728,  725,  726,
      727,  728,  945,  739,  749,  738,  758,  748,    0,    0,
      745,  755,    0,    0,  753,    0,  749,    0,  764,  754,
      763,    0,    0,  773,  778,  761,  782,    0,  779,  777,

      787,  790,  792,  792,  781,  790,  789,  803,  786,  787,
      806,  808,    0,  808,    0,  797,    0,  818,    0,    0,
      808,    0,    0,    0,  945,  945,  945,  817,  817,    0,
        0,    0,    0,  820,    0,    0,    0,  945,  945,  810,
        0,  945,  883,  890,  897,  904,  911,   92,  918,  924,
      931,  937
    } ;

static const flex_int16_t yy_def[453] =
    {   0,
      442,    1,  443,  443,    1,    1,  444,  444,  445,  445,
      443,  443,  446,  446,  442,  442,  442,  447,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  442,  442,  442,  442,  442,
      442,  449,  442,  450,  451,  442,  450,  452,  442,  442,
      447,  442,  442,  442,  442,  442,  442,  442,  442,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,

      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,   57,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  449,  442,  442,  442,
      442,  442,  451,  442,  452,  442,  442,  442,  442,  442,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,

      448,  448,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,

      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  442,  442,  442,  442,  442,  442,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,

      448,  448,  448,  442,  442,  442,  442,  442,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  442,  442,  442,  442,  442,  448,
      448,  448,  448,  448,  448,  448,  448,  442,  442,  448,
      448,    0,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442
    } ;

static const flex_int16_t yy_nxt[1027] =
    {   0,
       16,   17,   17,   17,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   43,   44,   45,   43,   43,   46,   47,   48,   49,
       43,   50,   51,   52,   43,   53,   54,   43,   43,   55,
       56,   57,   58,   16,   37,   38,   39,   40,   41,   42,
       43,   43,   44,   45,   43,   43,   46,   47,   48,   49,
       50,   51,   52,   43,   53,   54,   43,   43,   55,   59,
       60,   63,   63,   66,   69,   16,   66,   16,   69,   16,
       81,   16,   70,   70,   70,   70,   73,   80,   74,   77,

       78,   82,   84,   85,  216,   83,   87,   89,   75,   90,
       98,   99,  102,  100,  125,  153,   88,   86,  216,  101,
       81,  214,  214,  150,  103,   67,   64,   64,   67,  154,
      150,   82,   84,   85,   83,   91,   87,   89,   75,   90,
       98,   99,  102,  100,  125,  153,   88,   86,  101,   92,
       95,   72,   93,  103,   72,   94,  104,   96,   97,  154,
      107,  147,  109,  146,  148,   91,   73,  156,   74,  105,
      108,  442,  106,  110,  155,  157,  146,  111,   75,   92,
       95,   93,   79,   76,   94,   72,  104,   96,   97,  139,
      107,  147,  109,  118,  148,  112,  156,  119,  105,  113,

      108,  106,  114,  110,  155,  157,  111,  120,   75,  115,
      116,  149,  117,  149,  121,  144,  150,  160,  122,  442,
      140,  123,   61,  118,  141,  112,  142,  119,  124,  113,
       61,  442,  114,   70,   70,   70,   70,  120,  161,  115,
      116,  117,  162,  140,  121,  163,  160,  141,  122,  142,
      140,  123,  151,  141,  171,  142,  164,  165,  124,  126,
       70,   70,   70,   70,  175,  442,  166,  442,  161,  152,
      188,  442,  162,  140,  163,  158,  141,  442,  142,  167,
      159,  168,  151,  171,  127,  174,  164,  165,  169,  176,
      128,  172,  173,  175,  129,  130,  166,  131,  152,  188,

      132,  133,  442,  134,  135,  158,  170,  136,  177,  167,
      159,  168,  182,  185,  127,  174,  442,  191,  169,  176,
      128,  172,  173,  192,  129,  130,  186,  131,  178,  132,
      133,  183,  134,  135,  193,  170,  136,  179,  177,  187,
      194,  189,  182,  185,  180,  181,  190,  191,  195,  442,
      184,  196,  197,  192,  198,  199,  186,  200,  178,  201,
      202,  183,  203,  193,  206,  207,  204,  179,  187,  194,
      189,  208,  209,  180,  181,  190,  205,  195,  212,  184,
      210,  196,  197,  442,  198,  199,  211,  200,  217,  201,
      202,  218,  203,  221,  206,  207,  204,  222,  213,  223,

      213,  208,  209,  214,  219,  224,  205,  215,  212,  215,
      210,  225,  216,  220,  226,  442,  211,  217,  234,  235,
      218,  236,  442,  221,  237,  442,  239,  222,  223,  238,
      442,  240,  244,  241,  219,  224,  242,  243,  442,  245,
      246,  225,  247,  220,  226,  227,  248,  234,  228,  235,
      249,  236,  229,  250,  237,  230,  239,  231,  238,  232,
      240,  244,  233,  241,  253,  254,  242,  243,  245,  251,
      246,  247,  252,  255,  256,  227,  248,  257,  228,  249,
      258,  259,  229,  250,  260,  230,  231,  261,  232,  262,
      263,  233,  264,  253,  265,  254,  266,  267,  251,  268,

      269,  252,  270,  255,  256,  271,  272,  257,  273,  274,
      258,  259,  275,  260,  276,  277,  261,  278,  279,  262,
      263,  264,  280,  281,  265,  266,  282,  267,  268,  283,
      269,  284,  270,  285,  286,  271,  272,  287,  273,  274,
      288,  275,  289,  290,  276,  277,  292,  278,  279,  291,
      293,  295,  280,  281,  294,  296,  282,  297,  298,  283,
      299,  284,  285,  286,  300,  301,  287,  302,  303,  288,
      306,  307,  289,  290,  308,  309,  292,  304,  291,  305,
      293,  295,  310,  294,  311,  296,  312,  297,  298,  299,
      313,  314,  315,  300,  301,  316,  317,  302,  303,  318,

      306,  307,  319,  308,  320,  309,  324,  304,  325,  305,
      326,  310,  327,  311,  321,  312,  328,  329,  442,  330,
      313,  314,  315,  331,  332,  316,  317,  333,  334,  318,
      322,  323,  319,  335,  320,  336,  324,  337,  325,  338,
      326,  339,  327,  340,  321,  341,  328,  329,  330,  342,
      343,  442,  344,  331,  332,  345,  346,  333,  334,  322,
      323,  347,  348,  335,  349,  336,  337,  350,  353,  338,
      351,  339,  340,  352,  341,  354,  442,  355,  356,  342,
      343,  344,  357,  358,  359,  345,  346,  360,  361,  362,
      363,  347,  348,  349,  364,  442,  365,  350,  353,  351,

      366,  367,  352,  368,  369,  354,  355,  370,  356,  371,
      372,  374,  357,  358,  359,  373,  360,  375,  361,  362,
      363,  376,  377,  378,  364,  365,  379,  380,  381,  366,
      382,  367,  383,  368,  369,  384,  386,  370,  385,  371,
      372,  374,  387,  389,  373,  388,  390,  375,  391,  392,
      393,  376,  377,  378,  394,  379,  395,  380,  381,  396,
      382,  383,  397,  398,  399,  384,  386,  385,  400,  401,
      402,  403,  387,  389,  388,  404,  390,  391,  405,  392,
      393,  406,  407,  408,  394,  395,  409,  410,  411,  396,
      412,  397,  413,  398,  399,  414,  415,  400,  401,  402,

      403,  416,  417,  442,  418,  404,  419,  420,  405,  421,
      406,  422,  407,  408,  423,  409,  424,  410,  411,  412,
      425,  427,  413,  426,  414,  428,  415,  429,  442,  430,
      431,  416,  417,  418,  432,  433,  419,  420,  434,  421,
      435,  422,  436,  437,  423,  438,  424,  439,  440,  442,
      425,  427,  426,  441,  442,  428,  442,  429,  430,  431,
      442,  442,  442,  442,  432,  433,  442,  442,  434,  435,
      442,  442,  436,  437,  442,  438,  442,  439,  440,  442,
      442,  442,  441,   16,   16,   16,   16,   16,   16,   16,
       62,   62,   62,   62,   62,   62,   62,   65,   65,   65,

       65,   65,   65,   65,   68,   68,   68,   68,   68,   68,
       68,   71,   71,  442,   71,   71,   71,   71,  137,  137,
      137,  442,  137,  137,  138,  138,  138,  138,  138,  138,
      138,  143,  143,  143,  143,  442,  143,  145,  442,  442,
      145,  145,  145,  145,   15,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,

      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442
    } ;

static const flex_int16_t yy_chk[1027] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    8,    9,   13,   13,   10,   13,   14,   14,
       37,   14,   17,   17,   17,   17,   31,  448,   31,   34,

       34,   37,   38,   39,  216,   37,   40,   41,   31,   41,
       45,   46,   48,   47,   55,   82,   40,   39,  215,   47,
       37,  214,  213,  150,   48,    9,    7,    8,   10,   83,
      149,   37,   38,   39,   37,   42,   40,   41,   31,   41,
       45,   46,   48,   47,   55,   82,   40,   39,   47,   42,
       44,   72,   42,   48,   73,   42,   49,   44,   44,   83,
       50,   72,   51,  146,   73,   42,   74,   85,   74,   49,
       50,  126,   49,   51,   84,   86,   69,   51,   74,   42,
       44,   42,   36,   32,   42,   29,   49,   44,   44,   64,
       50,   72,   51,   53,   73,   52,   85,   53,   49,   52,

       50,   49,   52,   51,   84,   86,   51,   53,   74,   52,
       52,   75,   52,   75,   54,   67,   75,   89,   54,   15,
       64,   54,    6,   53,   64,   52,   64,   53,   54,   52,
        5,    0,   52,   61,   61,   61,   61,   53,   90,   52,
       52,   52,   91,   67,   54,   92,   89,   67,   54,   67,
       64,   54,   81,   64,  100,   64,   93,   94,   54,   57,
       70,   70,   70,   70,  104,    0,   96,    0,   90,   81,
      112,    0,   91,   67,   92,   87,   67,    0,   67,   97,
       87,   98,   81,  100,   57,  102,   93,   94,   99,  105,
       57,  101,  101,  104,   57,   57,   96,   57,   81,  112,

       57,   57,    0,   57,   57,   87,   99,   57,  106,   97,
       87,   98,  108,  110,   57,  102,    0,  114,   99,  105,
       57,  101,  101,  115,   57,   57,  111,   57,  107,   57,
       57,  109,   57,   57,  116,   99,   57,  107,  106,  111,
      117,  113,  108,  110,  107,  107,  113,  114,  118,    0,
      109,  119,  120,  115,  121,  122,  111,  123,  107,  124,
      125,  109,  127,  116,  129,  130,  128,  107,  111,  117,
      113,  131,  132,  107,  107,  113,  128,  118,  135,  109,
      133,  119,  120,    0,  121,  122,  133,  123,  151,  124,
      125,  152,  127,  155,  129,  130,  128,  156,  147,  157,

      147,  131,  132,  147,  154,  158,  128,  148,  135,  148,
      133,  159,  148,  154,  160,    0,  133,  151,  162,  164,
      152,  165,    0,  155,  166,    0,  168,  156,  157,  167,
        0,  169,  174,  170,  154,  158,  172,  173,    0,  175,
      176,  159,  177,  154,  160,  161,  178,  162,  161,  164,
      179,  165,  161,  180,  166,  161,  168,  161,  167,  161,
      169,  174,  161,  170,  182,  183,  172,  173,  175,  181,
      176,  177,  181,  184,  185,  161,  178,  186,  161,  179,
      187,  188,  161,  180,  189,  161,  161,  190,  161,  191,
      192,  161,  193,  182,  194,  183,  196,  197,  181,  198,

      199,  181,  200,  184,  185,  201,  202,  186,  203,  205,
      187,  188,  206,  189,  207,  208,  190,  209,  210,  191,
      192,  193,  211,  212,  194,  196,  217,  197,  198,  218,
      199,  219,  200,  220,  223,  201,  202,  224,  203,  205,
      225,  206,  226,  227,  207,  208,  228,  209,  210,  227,
      229,  231,  211,  212,  230,  232,  217,  233,  234,  218,
      237,  219,  220,  223,  238,  239,  224,  240,  241,  225,
      243,  247,  226,  227,  248,  249,  228,  241,  227,  241,
      229,  231,  250,  230,  251,  232,  252,  233,  234,  237,
      253,  254,  255,  238,  239,  256,  258,  240,  241,  263,

      243,  247,  264,  248,  266,  249,  269,  241,  270,  241,
      271,  250,  272,  251,  268,  252,  273,  274,    0,  275,
      253,  254,  255,  276,  277,  256,  258,  278,  279,  263,
      268,  268,  264,  280,  266,  281,  269,  282,  270,  283,
      271,  284,  272,  285,  268,  287,  273,  274,  275,  288,
      289,    0,  290,  276,  277,  291,  293,  278,  279,  268,
      268,  294,  295,  280,  296,  281,  282,  297,  302,  283,
      299,  284,  285,  301,  287,  303,    0,  306,  307,  288,
      289,  290,  308,  309,  312,  291,  293,  313,  314,  316,
      317,  294,  295,  296,  318,    0,  319,  297,  302,  299,

      320,  321,  301,  322,  323,  303,  306,  324,  307,  326,
      327,  330,  308,  309,  312,  329,  313,  331,  314,  316,
      317,  332,  333,  334,  318,  319,  338,  339,  340,  320,
      341,  321,  342,  322,  323,  345,  347,  324,  346,  326,
      327,  330,  348,  350,  329,  349,  352,  331,  354,  356,
      358,  332,  333,  334,  360,  338,  361,  339,  340,  362,
      341,  342,  364,  365,  368,  345,  347,  346,  369,  370,
      371,  372,  348,  350,  349,  374,  352,  354,  375,  356,
      358,  376,  377,  378,  360,  361,  381,  382,  385,  362,
      387,  364,  389,  365,  368,  390,  391,  369,  370,  371,

      372,  394,  395,    0,  396,  374,  397,  399,  375,  400,
      376,  401,  377,  378,  402,  381,  403,  382,  385,  387,
      404,  406,  389,  405,  390,  407,  391,  408,    0,  409,
      410,  394,  395,  396,  411,  412,  397,  399,  414,  400,
      416,  401,  418,  421,  402,  428,  403,  429,  434,    0,
      404,  406,  405,  440,    0,  407,    0,  408,  409,  410,
        0,    0,    0,    0,  411,  412,    0,    0,  414,  416,
        0,    0,  418,  421,    0,  428,    0,  429,  434,    0,
        0,    0,  440,  443,  443,  443,  443,  443,  443,  443,
      444,  444,  444,  444,  444,  444,  444,  445,  445,  445,

      445,  445,  445,  445,  446,  446,  446,  446,  446,  446,
      446,  447,  447,    0,  447,  447,  447,  447,  449,  449,
      449,    0,  449,  449,  450,  450,  450,  450,  450,  450,
      450,  451,  451,  451,  451,    0,  451,  452,    0,    0,
      452,  452,  452,  452,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,

      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[133] =
    {   0,
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static const flex_int16_t yy_rule_linenum[132] =
    {   0,
      173,  174,  175,  210,  229,  230,  232,  236,  241,  242,
      243,  244,  245,  247,  249,  250,  256,  261,  270,  271,
      272,  274,  275,  276,  277,  278,  279,  280,  281,  282,
      283,  284,  285,  286,  288,  289,  290,  291,  292,  293,
      294,  295,  296,  297,  298,  299,  300,  301,  302,  303,
      304,  305,  306,  307,  308,  309,  310,  311,  312,  313,
      314,  315,  316,  319,  320,  321,  322,  323,  324,  325,
      326,  327,  331,  332,  333,  334,  335,  336,  337,  338,
      339,  340,  341,  342,  343,  344,  345,  346,  348,  349,
      350,  351,  352,  355,  356,  357,  358,  359,  360,  361,

      362,  363,  364,  365,  366,  367,  371,  372,  373,  374,
      375,  376,  377,  378,  379,  380,  381,  382,  383,  384,
      386,  387,  388,  389,  390,  391,  392,  393,  394,  395,
      397
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <QString>
#include <string>
#include <stack>
#include <iostream>
#include <cerrno>
#include <climits>
#include <stdio.h>
#include <fstream>
#include "lexer.hpp"
typedef Language::Parser::token token;
#define yyterminate() return( token::END )
#define YY_NO_UNISTD_H // For msvc



using namespace Language;

#define YYERROR_VERBOSE 1
Language::location loc;//ÉùÃ÷Î»ÖÃÊµÀý

std::string cur_yytext;
std::string g_str;
int yycolumn = 1;
int yylineno = 1;
int current_line_indent = 0;   /* indentation of the current line */
int indent_level = 0;          /* indentation level passed to the parser */
std::stack<int> curr_indents;
int first_time = 1 ;

int parsing_error = 0;

std::stack<std::string> fileNames;
std::stack<int> lineNo;
std::vector<std::string> libPaths;



#define YY_USER_ACTION do { \
    if( loc.end.line < yylineno ) yycolumn = 1 ; \
    loc.begin.line = loc.end.line = yylineno; \
    loc.begin.column = yycolumn; loc.end.column = yycolumn + (int)yyleng - 1; \
    yycolumn += (int)yyleng; \
    loc.end.filename = &(fileNames.top()); \
    } while(0) ;

int yyerror(char const * s )
{
    printf("ERROR %s  at line %d col %d\n", s,  yylineno, yycolumn);
    printf("parsed %s %d.%d-%d.%d\n", loc.end.filename->c_str(), loc.begin.line, loc.begin.column, loc.end.line, loc.end.column);
    return 1;
}

#line 974 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"
 
#line 976 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"

#define INITIAL 0
#define indent 1
#define normal 2
#define str 3
#define qstr 4
#define comment 5
#define incl 6

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin.rdbuf(std::cin.rdbuf());
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout.rdbuf(std::cout.rdbuf());
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 160 "lexer.l"




#line 165 "lexer.l"
            if( first_time ) {
                first_time = 0;
                curr_indents.push(0);
                lineNo.push(yylineno);
                BEGIN normal;
            }

            
#line 1181 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 443 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 945 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 132 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 132 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 133 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 173 "lexer.l"
BEGIN(incl);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 174 "lexer.l"
/* eat the whitespace */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 175 "lexer.l"
{ /* got the include file name */
                    std::string fileName = yytext;
                    std::size_t pos = fileName.find(".liq");
                    if( pos == std::string::npos ) {
                        fileName += ".liq";
                    }
                    std::string filePath="";
                    for( auto libpath : libPaths ) {
                       filePath = libpath + fileName;
                       std::ifstream file(filePath.c_str());
                       if(file.good())
                          break;
                    }
                    std::filebuf fb;
                    if (fb.open (filePath,std::ios::in))
                    {
                         std::istream is(&fb);
                         //yyin = is;
                         fileNames.push(std::string(yytext));
                         lineNo.push(yylineno);
                         yylineno = yycolumn = 1;
                         loc.begin.line = loc.begin.column = loc.end.line = loc.end.column = 1;
                         yypush_buffer_state(yy_create_buffer( is, YY_BUF_SIZE ));
                         fb.close();
                    }
                    else
                    {
                         printf( "%s in %s line %d\n", (std::string("Failed to load import file ") + fileName).c_str(), fileNames.top().c_str(), yylineno );
                         parsing_error = 1;
                         yyterminate();
                    }

                    BEGIN(normal);
                    }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 210 "lexer.l"
{ current_line_indent = 0; /*BEGIN( indent);*/ yycolumn = 1; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(indent):
case YY_STATE_EOF(normal):
case YY_STATE_EOF(str):
case YY_STATE_EOF(qstr):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(incl):
#line 211 "lexer.l"
{
                   if( curr_indents.size() > 1 ) {
                        curr_indents.pop();
                        return token::UNINDENT;
                   }
                   if(lineNo.size() > 1 ) {
                       yypop_buffer_state();
                       fileNames.pop();
                       yylineno = lineNo.top();
                       lineNo.pop();
                   } else {
                        yyterminate();
                   }
                 }			 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 229 "lexer.l"
g_str = ""; BEGIN(str);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 230 "lexer.l"
g_str = ""; BEGIN(qstr);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 232 "lexer.l"
{   BEGIN(normal);
            yylval->sval = new QString(QString::fromStdString(g_str));
            return token::String;
        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 236 "lexer.l"
{   BEGIN(normal);
            yylval->sval = new QString(QString::fromStdString(g_str));
            return token::String;
        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 241 "lexer.l"
{g_str += "\n";}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 242 "lexer.l"
g_str += "\t";
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 243 "lexer.l"
g_str += "\r";
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 244 "lexer.l"
g_str += "\"";
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 245 "lexer.l"
g_str += "'";
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 247 "lexer.l"
{g_str += yytext[1]; cur_yytext=yytext[1];}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 249 "lexer.l"
{g_str += std::string(yytext);cur_yytext=yytext;}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 250 "lexer.l"
{g_str += std::string(yytext);cur_yytext=yytext;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 256 "lexer.l"
{
                                                        yylval->ival = atoi(yytext);
                                                        cur_yytext=yytext;
                                                        return token::LNumber;
                                                }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 261 "lexer.l"
{
                                                        yylval->dval = atof(yytext);
                                                        cur_yytext=yytext;
                                                        return token::Number;
                                                }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 270 "lexer.l"
{ return token::NumberType; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 271 "lexer.l"
{ return token::TextType; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 272 "lexer.l"
{ return token::VoidType; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 274 "lexer.l"
{ return token::WOBJ_P; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 275 "lexer.l"
{ return token::SEAM_NAME; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 276 "lexer.l"
{ return token::ZONE_P; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 277 "lexer.l"
{ return token::VEL_P; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 278 "lexer.l"
{ return token::TCP_P; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 279 "lexer.l"
{ return token::NOEOFFS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 280 "lexer.l"
{ return token::TOOL_P; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 281 "lexer.l"
{ return token::PLEN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 282 "lexer.l"
{ return token::MAXTIME; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 283 "lexer.l"
{ return token::TIMEFLAG; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 284 "lexer.l"
{ return token::INPOS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 285 "lexer.l"
{ return token::CONC; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 286 "lexer.l"
{ return token::ID_P; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 288 "lexer.l"
{ return token::NOT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 289 "lexer.l"
{ return token::IF; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 290 "lexer.l"
{return token::WELDDATA;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 291 "lexer.l"
{return token::SEAMDATA;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 292 "lexer.l"
{ return token::ELSE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 293 "lexer.l"
{ return token::ELSEIF; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 294 "lexer.l"
{ return token::THEN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 295 "lexer.l"
{ return token::ENDIF; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 296 "lexer.l"
{ return token::RETURN; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 297 "lexer.l"
{return token::WHILE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 298 "lexer.l"
{return token::DO;}   
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 299 "lexer.l"
{return token::ENDWHILE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 300 "lexer.l"
{return token::TEST;}   	
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 301 "lexer.l"
{return token::ENDTEST;}   	
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 302 "lexer.l"
{return token::PROC;}  
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 303 "lexer.l"
{return token::ENDPROC;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 304 "lexer.l"
{return token::CASE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 305 "lexer.l"
{return token::DEFAULT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 306 "lexer.l"
{return token::AND;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 307 "lexer.l"
{return token::OR;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 308 "lexer.l"
{ return token::MOD;}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 309 "lexer.l"
{}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 310 "lexer.l"
{return token::FTRUE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 311 "lexer.l"
{return token::FFALSE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 312 "lexer.l"
{return token::RETRY;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 313 "lexer.l"
{return token::FOR;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 314 "lexer.l"
{return token::TO;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 315 "lexer.l"
{return token::FROM;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 316 "lexer.l"
{return token::ENDFOR;}   
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 319 "lexer.l"
{return token::ACTUNIT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 320 "lexer.l"
{return token::MOVEABSJ;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 321 "lexer.l"
{return token::ARCLSTART;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 322 "lexer.l"
{return token::ARCL;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 323 "lexer.l"
{return token::ARCC;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 324 "lexer.l"
{return token::ARCEND;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 325 "lexer.l"
{return token::MOVEL;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 326 "lexer.l"
{return token::MOVEJ;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 327 "lexer.l"
{return token::DEACTUNIT;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 331 "lexer.l"
{return token::PERS;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 332 "lexer.l"
{return token::MODULE;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 333 "lexer.l"
{return token::ENDMODULE;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 334 "lexer.l"
{return token::TOOLDATA;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 335 "lexer.l"
{return token::SPEEDDATA;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 336 "lexer.l"
{return token::ZONEDATA;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 337 "lexer.l"
{return token::WOBJDATA;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 338 "lexer.l"
{return token::BOOL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 339 "lexer.l"
{return token::NUM;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 340 "lexer.l"
{return token::STRING;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 341 "lexer.l"
{return token::VAR;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 342 "lexer.l"
{return token::ROBTARGET;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 343 "lexer.l"
{return token::JOINTTARGET;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 344 "lexer.l"
{return token::CONST_L;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 345 "lexer.l"
{return token::TPWRITE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 346 "lexer.l"
{return token::FNULL;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 348 "lexer.l"
{return token::WAITTIME;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 349 "lexer.l"
{return token::SET;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 350 "lexer.l"
{return token::RESET;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 351 "lexer.l"
{return token::TASK;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 352 "lexer.l"
{return token::STEP;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 355 "lexer.l"
{return token::ACCSET;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 356 "lexer.l"
{return token::VELSET;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 357 "lexer.l"
{return token::SETDO;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 358 "lexer.l"
{return token::WAITDI;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 359 "lexer.l"
{return token::WAITUNTIL;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 360 "lexer.l"
{return token::OFFS;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 361 "lexer.l"
{return token::FUNC;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 362 "lexer.l"
{ return token::ENDFUNC; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 363 "lexer.l"
{return token::INOUT;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 364 "lexer.l"
{return token::RELTOOl;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 365 "lexer.l"
{return token::RECORD;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 366 "lexer.l"
{return token::ENDRECORD;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 367 "lexer.l"
{return token::PULSEDO;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 371 "lexer.l"
{return token::DOT;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 372 "lexer.l"
{return token::ASS;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 373 "lexer.l"
{return token::EQ;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 374 "lexer.l"
{ return token::SEMICOLON; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 375 "lexer.l"
{ return token::GE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 376 "lexer.l"
{ return token::NE; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 377 "lexer.l"
{ return token::LE; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 378 "lexer.l"
{ return token::LR; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 379 "lexer.l"
{ return token::RR; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 380 "lexer.l"
{ return token::COMMA; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 381 "lexer.l"
{ return token::LC; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 382 "lexer.l"
{ return token::RC; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 383 "lexer.l"
{ return token::LBRACE; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 384 "lexer.l"
{ return token::RBRACE; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 386 "lexer.l"
{return token::JIN;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 387 "lexer.l"
{ return token::ADD; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 388 "lexer.l"
{ return token::SUB; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 389 "lexer.l"
{ return token::DIVIDE; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 390 "lexer.l"
{ return token::MUL; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 391 "lexer.l"
{ return token::COLON; }  
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 392 "lexer.l"
{return token::LT;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 393 "lexer.l"
{return token::GT;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 394 "lexer.l"
{return token::DOLAR;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 395 "lexer.l"
/* comments one line til nl */
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 397 "lexer.l"
{
                                                        yylval->sval = new QString( yytext );
                                                        cur_yytext=yytext;
                                                        return( token::Identifier );
                                             }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 407 "lexer.l"
ECHO;
	YY_BREAK
#line 2009 "D:\\source\\repos\\rapid\\\\rapid\\lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 443 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 443 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 442);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, char* yy_bp)
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream& input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_input_file = file.rdbuf();
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int _new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 407 "lexer.l"






